/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'workerId' : IDL.Text,
  'checkIn' : IDL.Int,
  'totalHours' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'checkOut' : IDL.Opt(IDL.Int),
  'earlyLeaveMinutes' : IDL.Opt(IDL.Nat),
  'delayMinutes' : IDL.Opt(IDL.Nat),
  'overtimeMinutes' : IDL.Opt(IDL.Nat),
  'companyId' : IDL.Text,
});
export const PermissionRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'workerId' : IDL.Text,
  'hours' : IDL.Float64,
  'createdAt' : IDL.Int,
  'reason' : IDL.Text,
  'companyId' : IDL.Text,
});
export const CompanySettings = IDL.Record({
  'latitude' : IDL.Float64,
  'wifiSsid' : IDL.Opt(IDL.Text),
  'updatedAt' : IDL.Int,
  'longitude' : IDL.Float64,
  'radius' : IDL.Float64,
  'companyId' : IDL.Text,
});
export const CompanyTiming = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'updatedAt' : IDL.Int,
  'gracePeriodMinutes' : IDL.Nat,
  'companyId' : IDL.Text,
});
export const ManagerCredentials = IDL.Record({
  'keywordHash' : IDL.Text,
  'updatedAt' : IDL.Int,
  'pinHash' : IDL.Text,
  'companyId' : IDL.Text,
});
export const Worker = IDL.Record({
  'id' : IDL.Text,
  'faceEmbeddings' : IDL.Vec(IDL.Nat8),
  'name' : IDL.Text,
  'enrolledAt' : IDL.Int,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'companyId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'checkIn' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'checkOut' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'deleteWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAllPermissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PermissionRequest)],
      ['query'],
    ),
  'getAttendance' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByWorker' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCompanySettings' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CompanySettings)],
      ['query'],
    ),
  'getCompanyTiming' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CompanyTiming)],
      ['query'],
    ),
  'getManagerCredentials' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ManagerCredentials)],
      ['query'],
    ),
  'getPermissionRequests' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PermissionRequest)],
      ['query'],
    ),
  'getSyncVersion' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getWorker' : IDL.Func([IDL.Text, IDL.Text], [Worker], ['query']),
  'listWorkers' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
  'requestPermission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'setCompanySettings' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'setCompanyTiming' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'setManagerCredentials' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePermissionStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'workerId' : IDL.Text,
    'checkIn' : IDL.Int,
    'totalHours' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'checkOut' : IDL.Opt(IDL.Int),
    'earlyLeaveMinutes' : IDL.Opt(IDL.Nat),
    'delayMinutes' : IDL.Opt(IDL.Nat),
    'overtimeMinutes' : IDL.Opt(IDL.Nat),
    'companyId' : IDL.Text,
  });
  const PermissionRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'workerId' : IDL.Text,
    'hours' : IDL.Float64,
    'createdAt' : IDL.Int,
    'reason' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const CompanySettings = IDL.Record({
    'latitude' : IDL.Float64,
    'wifiSsid' : IDL.Opt(IDL.Text),
    'updatedAt' : IDL.Int,
    'longitude' : IDL.Float64,
    'radius' : IDL.Float64,
    'companyId' : IDL.Text,
  });
  const CompanyTiming = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'updatedAt' : IDL.Int,
    'gracePeriodMinutes' : IDL.Nat,
    'companyId' : IDL.Text,
  });
  const ManagerCredentials = IDL.Record({
    'keywordHash' : IDL.Text,
    'updatedAt' : IDL.Int,
    'pinHash' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const Worker = IDL.Record({
    'id' : IDL.Text,
    'faceEmbeddings' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'enrolledAt' : IDL.Int,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'companyId' : IDL.Text,
  });
  
  return IDL.Service({
    'addWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'checkIn' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'checkOut' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'deleteWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAllPermissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PermissionRequest)],
        ['query'],
      ),
    'getAttendance' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByWorker' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCompanySettings' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CompanySettings)],
        ['query'],
      ),
    'getCompanyTiming' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CompanyTiming)],
        ['query'],
      ),
    'getManagerCredentials' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ManagerCredentials)],
        ['query'],
      ),
    'getPermissionRequests' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PermissionRequest)],
        ['query'],
      ),
    'getSyncVersion' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getWorker' : IDL.Func([IDL.Text, IDL.Text], [Worker], ['query']),
    'listWorkers' : IDL.Func([IDL.Text], [IDL.Vec(Worker)], ['query']),
    'requestPermission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'setCompanySettings' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'setCompanyTiming' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'setManagerCredentials' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePermissionStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };