/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'status' : string,
  'workerId' : string,
  'checkIn' : bigint,
  'totalHours' : [] | [number],
  'date' : string,
  'checkOut' : [] | [bigint],
  'earlyLeaveMinutes' : [] | [bigint],
  'delayMinutes' : [] | [bigint],
  'overtimeMinutes' : [] | [bigint],
  'companyId' : string,
}
export interface CompanySettings {
  'latitude' : number,
  'wifiSsid' : [] | [string],
  'updatedAt' : bigint,
  'longitude' : number,
  'radius' : number,
  'companyId' : string,
}
export interface CompanyTiming {
  'id' : string,
  'startTime' : string,
  'endTime' : string,
  'updatedAt' : bigint,
  'gracePeriodMinutes' : bigint,
  'companyId' : string,
}
export interface ManagerCredentials {
  'keywordHash' : string,
  'updatedAt' : bigint,
  'pinHash' : string,
  'companyId' : string,
}
export interface PermissionRequest {
  'id' : string,
  'status' : string,
  'workerId' : string,
  'hours' : number,
  'createdAt' : bigint,
  'reason' : string,
  'companyId' : string,
}
export interface Worker {
  'id' : string,
  'faceEmbeddings' : Uint8Array,
  'name' : string,
  'enrolledAt' : bigint,
  'phone' : string,
  'department' : string,
  'companyId' : string,
}
export interface _SERVICE {
  'addWorker' : ActorMethod<
    [string, string, string, string, string, Uint8Array],
    undefined
  >,
  'checkIn' : ActorMethod<[string, string, string, [] | [bigint]], undefined>,
  'checkOut' : ActorMethod<
    [string, string, string, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'deleteWorker' : ActorMethod<[string, string], undefined>,
  'getAllAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAllPermissions' : ActorMethod<[string], Array<PermissionRequest>>,
  'getAttendance' : ActorMethod<
    [string, string, string],
    [] | [AttendanceRecord]
  >,
  'getAttendanceByWorker' : ActorMethod<
    [string, string],
    Array<AttendanceRecord>
  >,
  'getCompanySettings' : ActorMethod<[string], [] | [CompanySettings]>,
  'getCompanyTiming' : ActorMethod<[string], [] | [CompanyTiming]>,
  'getManagerCredentials' : ActorMethod<[string], [] | [ManagerCredentials]>,
  'getPermissionRequests' : ActorMethod<
    [string, string],
    Array<PermissionRequest>
  >,
  'getSyncVersion' : ActorMethod<[string], bigint>,
  'getWorker' : ActorMethod<[string, string], Worker>,
  'listWorkers' : ActorMethod<[string], Array<Worker>>,
  'requestPermission' : ActorMethod<
    [string, string, string, number],
    undefined
  >,
  'setCompanySettings' : ActorMethod<
    [string, number, number, number, [] | [string]],
    undefined
  >,
  'setCompanyTiming' : ActorMethod<[string, string, string, bigint], undefined>,
  'setManagerCredentials' : ActorMethod<[string, string, string], undefined>,
  'updatePermissionStatus' : ActorMethod<[string, string, string], undefined>,
  'updateWorker' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];